generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Paymentdoc
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          paymentdoc
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:
          label: Создан
        order_id:
          label: Заказ
        payment_type:
          label: Тип платежной системы
        amount:
          label: Сумма в копейках
      list:
        title: Документы оплаты
        display: [ created_at, order_id, amount, payment_type ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
