generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ActionsDiscount
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          actions_discount
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        startaction:
          label: Начало акции
        endaction:
          label: Конец акции
        text:
          label: Текст купона
        discount:
          label: Скидка
      list:    
        sort: [id, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
