<?php

/**
 * BaseAtolsettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $token
 * 
 * @method clob         getToken() Returns the current record's "token" value
 * @method Atolsettings setToken() Sets the current record's "token" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAtolsettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('atolsettings');
        $this->hasColumn('token', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}