<?php

/**
 * BaseFastOrderLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property string $username
 * @property string $mail
 * 
 * @method string       getCode()     Returns the current record's "code" value
 * @method string       getName()     Returns the current record's "name" value
 * @method string       getUsername() Returns the current record's "username" value
 * @method string       getMail()     Returns the current record's "mail" value
 * @method FastOrderLog setCode()     Sets the current record's "code" value
 * @method FastOrderLog setName()     Sets the current record's "name" value
 * @method FastOrderLog setUsername() Sets the current record's "username" value
 * @method FastOrderLog setMail()     Sets the current record's "mail" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFastOrderLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fast_order_log');
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}