<?php

/**
 * BaseWheelsectors
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $percent
 * @property integer $discount
 * @property Array $coupon
 * @property enum $color
 * 
 * @method integer      getPercent()  Returns the current record's "percent" value
 * @method integer      getDiscount() Returns the current record's "discount" value
 * @method Array        getCoupon()   Returns the current record's "coupon" value
 * @method enum         getColor()    Returns the current record's "color" value
 * @method Wheelsectors setPercent()  Sets the current record's "percent" value
 * @method Wheelsectors setDiscount() Sets the current record's "discount" value
 * @method Wheelsectors setCoupon()   Sets the current record's "coupon" value
 * @method Wheelsectors setColor()    Sets the current record's "color" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWheelsectors extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wheelsectors');
        $this->hasColumn('percent', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('discount', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('coupon', 'Array', null, array(
             'type' => 'Array',
             ));
        $this->hasColumn('color', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Синий',
              1 => 'Оранжевый',
              2 => 'Зеленый',
              3 => 'Красный',
              4 => 'Желтый',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}