<?php

/**
 * BasePartnerRefid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $refid
 * 
 * @method string       getRefid() Returns the current record's "refid" value
 * @method PartnerRefid setRefid() Sets the current record's "refid" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartnerRefid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner_refid');
        $this->hasColumn('refid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}