<?php

/**
 * BaseActionsDiscount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $startaction
 * @property timestamp $endaction
 * @property string $text
 * @property integer $discount
 * @property Doctrine_Collection $Interval
 * 
 * @method timestamp           getStartaction() Returns the current record's "startaction" value
 * @method timestamp           getEndaction()   Returns the current record's "endaction" value
 * @method string              getText()        Returns the current record's "text" value
 * @method integer             getDiscount()    Returns the current record's "discount" value
 * @method Doctrine_Collection getInterval()    Returns the current record's "Interval" collection
 * @method ActionsDiscount     setStartaction() Sets the current record's "startaction" value
 * @method ActionsDiscount     setEndaction()   Sets the current record's "endaction" value
 * @method ActionsDiscount     setText()        Sets the current record's "text" value
 * @method ActionsDiscount     setDiscount()    Sets the current record's "discount" value
 * @method ActionsDiscount     setInterval()    Sets the current record's "Interval" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActionsDiscount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actions_discount');
        $this->hasColumn('startaction', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('endaction', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('discount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ActionsDiscountInterval as Interval', array(
             'local' => 'id',
             'foreign' => 'actionsdiscount_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}