<?php

/**
 * BaseServicerequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $fio
 * @property string $email
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer        getUserId()      Returns the current record's "user_id" value
 * @method string         getFio()         Returns the current record's "fio" value
 * @method string         getEmail()       Returns the current record's "email" value
 * @method sfGuardUser    getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Servicerequest setUserId()      Sets the current record's "user_id" value
 * @method Servicerequest setFio()         Sets the current record's "fio" value
 * @method Servicerequest setEmail()       Sets the current record's "email" value
 * @method Servicerequest setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicerequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicerequest');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('fio', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}