<?php

/**
 * BaseOrdersPayments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $order_id
 * @property string $payment_id
 * @property string $idempotence
 * @property string $payment_service
 * @property string $status
 * 
 * @method integer        getOrderId()         Returns the current record's "order_id" value
 * @method string         getPaymentId()       Returns the current record's "payment_id" value
 * @method string         getIdempotence()     Returns the current record's "idempotence" value
 * @method string         getPaymentService()  Returns the current record's "payment_service" value
 * @method string         getStatus()          Returns the current record's "status" value
 * @method OrdersPayments setOrderId()         Sets the current record's "order_id" value
 * @method OrdersPayments setPaymentId()       Sets the current record's "payment_id" value
 * @method OrdersPayments setIdempotence()     Sets the current record's "idempotence" value
 * @method OrdersPayments setPaymentService()  Sets the current record's "payment_service" value
 * @method OrdersPayments setStatus()          Sets the current record's "status" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdersPayments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orders_payments');
        $this->hasColumn('order_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 8,
             ));
        $this->hasColumn('payment_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('idempotence', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('payment_service', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}