<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $h1
 * @property string $name
 * @property string $code
 * @property clob $content
 * @property clob $newbie_description
 * @property integer $price
 * @property integer $bonus
 * @property integer $bonuspay
 * @property integer $old_price
 * @property integer $discount
 * @property integer $nextdiscount
 * @property integer $count
 * @property string $video
 * @property string $doc1
 * @property string $doc2
 * @property string $doc3
 * @property string $doc4
 * @property string $doc5
 * @property string $articles_ids
 * @property string $file
 * @property string $canonical
 * @property boolean $videoenabled
 * @property boolean $is_coupon_enabled
 * @property boolean $is_bonus_enabled
 * @property integer $views_count
 * @property integer $votes_count
 * @property integer $rating
 * @property boolean $is_related
 * @property boolean $is_public
 * @property boolean $is_new_on_market
 * @property boolean $is_new_on_site
 * @property boolean $is_visiblechildren
 * @property boolean $is_visiblecategory
 * @property boolean $is_notadddelivery
 * @property boolean $set_pairs
 * @property boolean $set_her
 * @property boolean $set_him
 * @property boolean $for_pairs
 * @property boolean $for_she
 * @property boolean $for_her
 * @property boolean $bdsm
 * @property boolean $cosmetics
 * @property boolean $belie
 * @property boolean $other
 * @property boolean $sync
 * @property string $title
 * @property string $externallink
 * @property string $keywords
 * @property string $description
 * @property integer $parents_id
 * @property string $id1c
 * @property integer $generalcategory_id
 * @property boolean $adult
 * @property boolean $yamarket
 * @property boolean $is_express
 * @property date $endaction
 * @property date $startaction
 * @property enum $step
 * @property integer $positionrelated
 * @property string $tags
 * @property string $pointcreate
 * @property boolean $moder
 * @property string $moderuser
 * @property string $user
 * @property boolean $yamarket_clothes
 * @property string $yamarket_color
 * @property string $yamarket_typeimg
 * @property string $yamarket_category
 * @property enum $yamarket_sex
 * @property string $yamarket_model
 * @property string $yamarket_typeprefix
 * @property clob $stock
 * @property clob $buywithitem
 * @property integer $countsell
 * @property integer $sortpriority
 * @property string $barcode
 * @property float $weight
 * @property Doctrine_Collection $CategoryProducts
 * @property Doctrine_Collection $DopInfoProducts
 * @property Product $Parent
 * @property Doctrine_Collection $Children
 * @property Category $GeneralCategory
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $Photoalbums
 * @property Doctrine_Collection $ProductPhotoalbums
 * 
 * @method string              getH1()                  Returns the current record's "h1" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getCode()                Returns the current record's "code" value
 * @method clob                getContent()             Returns the current record's "content" value
 * @method clob                getNewbieDescription()   Returns the current record's "newbie_description" value
 * @method integer             getPrice()               Returns the current record's "price" value
 * @method integer             getBonus()               Returns the current record's "bonus" value
 * @method integer             getBonuspay()            Returns the current record's "bonuspay" value
 * @method integer             getOldPrice()            Returns the current record's "old_price" value
 * @method integer             getDiscount()            Returns the current record's "discount" value
 * @method integer             getNextdiscount()        Returns the current record's "nextdiscount" value
 * @method integer             getCount()               Returns the current record's "count" value
 * @method string              getVideo()               Returns the current record's "video" value
 * @method string              getDoc1()                Returns the current record's "doc1" value
 * @method string              getDoc2()                Returns the current record's "doc2" value
 * @method string              getDoc3()                Returns the current record's "doc3" value
 * @method string              getDoc4()                Returns the current record's "doc4" value
 * @method string              getDoc5()                Returns the current record's "doc5" value
 * @method string              getArticlesIds()         Returns the current record's "articles_ids" value
 * @method string              getFile()                Returns the current record's "file" value
 * @method string              getCanonical()           Returns the current record's "canonical" value
 * @method boolean             getVideoenabled()        Returns the current record's "videoenabled" value
 * @method boolean             getIsCouponEnabled()     Returns the current record's "is_coupon_enabled" value
 * @method boolean             getIsBonusEnabled()      Returns the current record's "is_bonus_enabled" value
 * @method integer             getViewsCount()          Returns the current record's "views_count" value
 * @method integer             getVotesCount()          Returns the current record's "votes_count" value
 * @method integer             getRating()              Returns the current record's "rating" value
 * @method boolean             getIsRelated()           Returns the current record's "is_related" value
 * @method boolean             getIsPublic()            Returns the current record's "is_public" value
 * @method boolean             getIsNewOnMarket()       Returns the current record's "is_new_on_market" value
 * @method boolean             getIsNewOnSite()         Returns the current record's "is_new_on_site" value
 * @method boolean             getIsVisiblechildren()   Returns the current record's "is_visiblechildren" value
 * @method boolean             getIsVisiblecategory()   Returns the current record's "is_visiblecategory" value
 * @method boolean             getIsNotadddelivery()    Returns the current record's "is_notadddelivery" value
 * @method boolean             getSetPairs()            Returns the current record's "set_pairs" value
 * @method boolean             getSetHer()              Returns the current record's "set_her" value
 * @method boolean             getSetHim()              Returns the current record's "set_him" value
 * @method boolean             getForPairs()            Returns the current record's "for_pairs" value
 * @method boolean             getForShe()              Returns the current record's "for_she" value
 * @method boolean             getForHer()              Returns the current record's "for_her" value
 * @method boolean             getBdsm()                Returns the current record's "bdsm" value
 * @method boolean             getCosmetics()           Returns the current record's "cosmetics" value
 * @method boolean             getBelie()               Returns the current record's "belie" value
 * @method boolean             getOther()               Returns the current record's "other" value
 * @method boolean             getSync()                Returns the current record's "sync" value
 * @method string              getTitle()               Returns the current record's "title" value
 * @method string              getExternallink()        Returns the current record's "externallink" value
 * @method string              getKeywords()            Returns the current record's "keywords" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getParentsId()           Returns the current record's "parents_id" value
 * @method string              getId1c()                Returns the current record's "id1c" value
 * @method integer             getGeneralcategoryId()   Returns the current record's "generalcategory_id" value
 * @method boolean             getAdult()               Returns the current record's "adult" value
 * @method boolean             getYamarket()            Returns the current record's "yamarket" value
 * @method boolean             getIsExpress()           Returns the current record's "is_express" value
 * @method date                getEndaction()           Returns the current record's "endaction" value
 * @method date                getStartaction()         Returns the current record's "startaction" value
 * @method enum                getStep()                Returns the current record's "step" value
 * @method integer             getPositionrelated()     Returns the current record's "positionrelated" value
 * @method string              getTags()                Returns the current record's "tags" value
 * @method string              getPointcreate()         Returns the current record's "pointcreate" value
 * @method boolean             getModer()               Returns the current record's "moder" value
 * @method string              getModeruser()           Returns the current record's "moderuser" value
 * @method string              getUser()                Returns the current record's "user" value
 * @method boolean             getYamarketClothes()     Returns the current record's "yamarket_clothes" value
 * @method string              getYamarketColor()       Returns the current record's "yamarket_color" value
 * @method string              getYamarketTypeimg()     Returns the current record's "yamarket_typeimg" value
 * @method string              getYamarketCategory()    Returns the current record's "yamarket_category" value
 * @method enum                getYamarketSex()         Returns the current record's "yamarket_sex" value
 * @method string              getYamarketModel()       Returns the current record's "yamarket_model" value
 * @method string              getYamarketTypeprefix()  Returns the current record's "yamarket_typeprefix" value
 * @method clob                getStock()               Returns the current record's "stock" value
 * @method clob                getBuywithitem()         Returns the current record's "buywithitem" value
 * @method integer             getCountsell()           Returns the current record's "countsell" value
 * @method integer             getSortpriority()        Returns the current record's "sortpriority" value
 * @method string              getBarcode()             Returns the current record's "barcode" value
 * @method float               getWeight()              Returns the current record's "weight" value
 * @method Doctrine_Collection getCategoryProducts()    Returns the current record's "CategoryProducts" collection
 * @method Doctrine_Collection getDopInfoProducts()     Returns the current record's "DopInfoProducts" collection
 * @method Product             getParent()              Returns the current record's "Parent" value
 * @method Doctrine_Collection getChildren()            Returns the current record's "Children" collection
 * @method Category            getGeneralCategory()     Returns the current record's "GeneralCategory" value
 * @method Doctrine_Collection getComments()            Returns the current record's "Comments" collection
 * @method Doctrine_Collection getPhotoalbums()         Returns the current record's "Photoalbums" collection
 * @method Doctrine_Collection getProductPhotoalbums()  Returns the current record's "ProductPhotoalbums" collection
 * @method Product             setH1()                  Sets the current record's "h1" value
 * @method Product             setName()                Sets the current record's "name" value
 * @method Product             setCode()                Sets the current record's "code" value
 * @method Product             setContent()             Sets the current record's "content" value
 * @method Product             setNewbieDescription()   Sets the current record's "newbie_description" value
 * @method Product             setPrice()               Sets the current record's "price" value
 * @method Product             setBonus()               Sets the current record's "bonus" value
 * @method Product             setBonuspay()            Sets the current record's "bonuspay" value
 * @method Product             setOldPrice()            Sets the current record's "old_price" value
 * @method Product             setDiscount()            Sets the current record's "discount" value
 * @method Product             setNextdiscount()        Sets the current record's "nextdiscount" value
 * @method Product             setCount()               Sets the current record's "count" value
 * @method Product             setVideo()               Sets the current record's "video" value
 * @method Product             setDoc1()                Sets the current record's "doc1" value
 * @method Product             setDoc2()                Sets the current record's "doc2" value
 * @method Product             setDoc3()                Sets the current record's "doc3" value
 * @method Product             setDoc4()                Sets the current record's "doc4" value
 * @method Product             setDoc5()                Sets the current record's "doc5" value
 * @method Product             setArticlesIds()         Sets the current record's "articles_ids" value
 * @method Product             setFile()                Sets the current record's "file" value
 * @method Product             setCanonical()           Sets the current record's "canonical" value
 * @method Product             setVideoenabled()        Sets the current record's "videoenabled" value
 * @method Product             setIsCouponEnabled()     Sets the current record's "is_coupon_enabled" value
 * @method Product             setIsBonusEnabled()      Sets the current record's "is_bonus_enabled" value
 * @method Product             setViewsCount()          Sets the current record's "views_count" value
 * @method Product             setVotesCount()          Sets the current record's "votes_count" value
 * @method Product             setRating()              Sets the current record's "rating" value
 * @method Product             setIsRelated()           Sets the current record's "is_related" value
 * @method Product             setIsPublic()            Sets the current record's "is_public" value
 * @method Product             setIsNewOnMarket()       Sets the current record's "is_new_on_market" value
 * @method Product             setIsNewOnSite()         Sets the current record's "is_new_on_site" value
 * @method Product             setIsVisiblechildren()   Sets the current record's "is_visiblechildren" value
 * @method Product             setIsVisiblecategory()   Sets the current record's "is_visiblecategory" value
 * @method Product             setIsNotadddelivery()    Sets the current record's "is_notadddelivery" value
 * @method Product             setSetPairs()            Sets the current record's "set_pairs" value
 * @method Product             setSetHer()              Sets the current record's "set_her" value
 * @method Product             setSetHim()              Sets the current record's "set_him" value
 * @method Product             setForPairs()            Sets the current record's "for_pairs" value
 * @method Product             setForShe()              Sets the current record's "for_she" value
 * @method Product             setForHer()              Sets the current record's "for_her" value
 * @method Product             setBdsm()                Sets the current record's "bdsm" value
 * @method Product             setCosmetics()           Sets the current record's "cosmetics" value
 * @method Product             setBelie()               Sets the current record's "belie" value
 * @method Product             setOther()               Sets the current record's "other" value
 * @method Product             setSync()                Sets the current record's "sync" value
 * @method Product             setTitle()               Sets the current record's "title" value
 * @method Product             setExternallink()        Sets the current record's "externallink" value
 * @method Product             setKeywords()            Sets the current record's "keywords" value
 * @method Product             setDescription()         Sets the current record's "description" value
 * @method Product             setParentsId()           Sets the current record's "parents_id" value
 * @method Product             setId1c()                Sets the current record's "id1c" value
 * @method Product             setGeneralcategoryId()   Sets the current record's "generalcategory_id" value
 * @method Product             setAdult()               Sets the current record's "adult" value
 * @method Product             setYamarket()            Sets the current record's "yamarket" value
 * @method Product             setIsExpress()           Sets the current record's "is_express" value
 * @method Product             setEndaction()           Sets the current record's "endaction" value
 * @method Product             setStartaction()         Sets the current record's "startaction" value
 * @method Product             setStep()                Sets the current record's "step" value
 * @method Product             setPositionrelated()     Sets the current record's "positionrelated" value
 * @method Product             setTags()                Sets the current record's "tags" value
 * @method Product             setPointcreate()         Sets the current record's "pointcreate" value
 * @method Product             setModer()               Sets the current record's "moder" value
 * @method Product             setModeruser()           Sets the current record's "moderuser" value
 * @method Product             setUser()                Sets the current record's "user" value
 * @method Product             setYamarketClothes()     Sets the current record's "yamarket_clothes" value
 * @method Product             setYamarketColor()       Sets the current record's "yamarket_color" value
 * @method Product             setYamarketTypeimg()     Sets the current record's "yamarket_typeimg" value
 * @method Product             setYamarketCategory()    Sets the current record's "yamarket_category" value
 * @method Product             setYamarketSex()         Sets the current record's "yamarket_sex" value
 * @method Product             setYamarketModel()       Sets the current record's "yamarket_model" value
 * @method Product             setYamarketTypeprefix()  Sets the current record's "yamarket_typeprefix" value
 * @method Product             setStock()               Sets the current record's "stock" value
 * @method Product             setBuywithitem()         Sets the current record's "buywithitem" value
 * @method Product             setCountsell()           Sets the current record's "countsell" value
 * @method Product             setSortpriority()        Sets the current record's "sortpriority" value
 * @method Product             setBarcode()             Sets the current record's "barcode" value
 * @method Product             setWeight()              Sets the current record's "weight" value
 * @method Product             setCategoryProducts()    Sets the current record's "CategoryProducts" collection
 * @method Product             setDopInfoProducts()     Sets the current record's "DopInfoProducts" collection
 * @method Product             setParent()              Sets the current record's "Parent" value
 * @method Product             setChildren()            Sets the current record's "Children" collection
 * @method Product             setGeneralCategory()     Sets the current record's "GeneralCategory" value
 * @method Product             setComments()            Sets the current record's "Comments" collection
 * @method Product             setPhotoalbums()         Sets the current record's "Photoalbums" collection
 * @method Product             setProductPhotoalbums()  Sets the current record's "ProductPhotoalbums" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('newbie_description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bonus', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bonuspay', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('old_price', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('discount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nextdiscount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('video', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc4', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('doc5', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('articles_ids', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('canonical', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('videoenabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_coupon_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_bonus_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('views_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('votes_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_related', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_new_on_market', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_new_on_site', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_visiblechildren', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_visiblecategory', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_notadddelivery', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('set_pairs', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('set_her', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('set_him', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('for_pairs', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('for_she', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('for_her', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('bdsm', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('cosmetics', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('belie', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('other', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('sync', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('externallink', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('parents_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('id1c', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('generalcategory_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('adult', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('yamarket', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_express', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('endaction', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('startaction', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('step', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '',
              1 => '1 сутки',
              2 => '2 суток',
              3 => '3 суток',
              4 => '4 суток',
              5 => '5 суток',
             ),
             ));
        $this->hasColumn('positionrelated', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pointcreate', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('moder', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('moderuser', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('yamarket_clothes', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('yamarket_color', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('yamarket_typeimg', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('yamarket_category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('yamarket_sex', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '',
              1 => 'Женский',
              2 => 'Мужской',
             ),
             ));
        $this->hasColumn('yamarket_model', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('yamarket_typeprefix', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('stock', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('buywithitem', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('countsell', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('sortpriority', 'integer', 8, array(
             'type' => 'integer',
             'default' => 50,
             'length' => 8,
             ));
        $this->hasColumn('barcode', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('weight', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as CategoryProducts', array(
             'refClass' => 'CategoryProduct',
             'local' => 'product_id',
             'foreign' => 'category_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('DopInfo as DopInfoProducts', array(
             'refClass' => 'DopInfoProduct',
             'local' => 'product_id',
             'foreign' => 'dop_info_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product as Parent', array(
             'local' => 'parents_id',
             'foreign' => 'id'));

        $this->hasMany('Product as Children', array(
             'local' => 'id',
             'foreign' => 'parents_id'));

        $this->hasOne('Category as GeneralCategory', array(
             'local' => 'generalcategory_id',
             'foreign' => 'id'));

        $this->hasMany('Comments', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Photoalbum as Photoalbums', array(
             'refClass' => 'ProductPhotoalbum',
             'local' => 'product_id',
             'foreign' => 'photoalbum_id'));

        $this->hasMany('ProductPhotoalbum as ProductPhotoalbums', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => false,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($sluggable0);
    }
}