<?php

/**
 * BaseDopInfoCategoryFullDopInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dop_info_category_full_id
 * @property integer $dop_info_id
 * @property DopInfoCategoryFull $DopInfoCategoryFull
 * @property DopInfo $DopInfo
 * 
 * @method integer                    getDopInfoCategoryFullId()     Returns the current record's "dop_info_category_full_id" value
 * @method integer                    getDopInfoId()                 Returns the current record's "dop_info_id" value
 * @method DopInfoCategoryFull        getDopInfoCategoryFull()       Returns the current record's "DopInfoCategoryFull" value
 * @method DopInfo                    getDopInfo()                   Returns the current record's "DopInfo" value
 * @method DopInfoCategoryFullDopInfo setDopInfoCategoryFullId()     Sets the current record's "dop_info_category_full_id" value
 * @method DopInfoCategoryFullDopInfo setDopInfoId()                 Sets the current record's "dop_info_id" value
 * @method DopInfoCategoryFullDopInfo setDopInfoCategoryFull()       Sets the current record's "DopInfoCategoryFull" value
 * @method DopInfoCategoryFullDopInfo setDopInfo()                   Sets the current record's "DopInfo" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDopInfoCategoryFullDopInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dop_info_category_full_dop_info');
        $this->hasColumn('dop_info_category_full_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('dop_info_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DopInfoCategoryFull', array(
             'local' => 'dop_info_category_full_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DopInfo', array(
             'local' => 'dop_info_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}