<?php

/**
 * BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $content
 * @property boolean $is_public
 * @property string $picture
 * @property string $picturehover
 * @property string $description
 * @property boolean $is_online
 * @property Doctrine_Collection $Deliverys
 * @property Doctrine_Collection $DeliveryPayment
 * @property Doctrine_Collection $Payment
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method clob                getContent()         Returns the current record's "content" value
 * @method boolean             getIsPublic()        Returns the current record's "is_public" value
 * @method string              getPicture()         Returns the current record's "picture" value
 * @method string              getPicturehover()    Returns the current record's "picturehover" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method boolean             getIsOnline()        Returns the current record's "is_online" value
 * @method Doctrine_Collection getDeliverys()       Returns the current record's "Deliverys" collection
 * @method Doctrine_Collection getDeliveryPayment() Returns the current record's "DeliveryPayment" collection
 * @method Doctrine_Collection getPayment()         Returns the current record's "Payment" collection
 * @method Payment             setName()            Sets the current record's "name" value
 * @method Payment             setContent()         Sets the current record's "content" value
 * @method Payment             setIsPublic()        Sets the current record's "is_public" value
 * @method Payment             setPicture()         Sets the current record's "picture" value
 * @method Payment             setPicturehover()    Sets the current record's "picturehover" value
 * @method Payment             setDescription()     Sets the current record's "description" value
 * @method Payment             setIsOnline()        Sets the current record's "is_online" value
 * @method Payment             setDeliverys()       Sets the current record's "Deliverys" collection
 * @method Payment             setDeliveryPayment() Sets the current record's "DeliveryPayment" collection
 * @method Payment             setPayment()         Sets the current record's "Payment" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('picturehover', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('is_online', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Delivery as Deliverys', array(
             'refClass' => 'DeliveryPayment',
             'local' => 'payment_id',
             'foreign' => 'delivery_id'));

        $this->hasMany('DeliveryPayment', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $this->hasMany('Orders as Payment', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}