<?php

/**
 * BaseQuizResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quiz_id
 * @property string $name
 * @property integer $balls_to
 * @property integer $balls_from
 * @property clob $results
 * @property string $link
 * @property string $link_1
 * @property string $link_2
 * @property Quiz $Quiz
 * 
 * @method integer    getQuizId()     Returns the current record's "quiz_id" value
 * @method string     getName()       Returns the current record's "name" value
 * @method integer    getBallsTo()    Returns the current record's "balls_to" value
 * @method integer    getBallsFrom()  Returns the current record's "balls_from" value
 * @method clob       getResults()    Returns the current record's "results" value
 * @method string     getLink()       Returns the current record's "link" value
 * @method string     getLink1()      Returns the current record's "link_1" value
 * @method string     getLink2()      Returns the current record's "link_2" value
 * @method Quiz       getQuiz()       Returns the current record's "Quiz" value
 * @method QuizResult setQuizId()     Sets the current record's "quiz_id" value
 * @method QuizResult setName()       Sets the current record's "name" value
 * @method QuizResult setBallsTo()    Sets the current record's "balls_to" value
 * @method QuizResult setBallsFrom()  Sets the current record's "balls_from" value
 * @method QuizResult setResults()    Sets the current record's "results" value
 * @method QuizResult setLink()       Sets the current record's "link" value
 * @method QuizResult setLink1()      Sets the current record's "link_1" value
 * @method QuizResult setLink2()      Sets the current record's "link_2" value
 * @method QuizResult setQuiz()       Sets the current record's "Quiz" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizResult extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_result');
        $this->hasColumn('quiz_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('balls_to', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('balls_from', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('results', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link_1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link_2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}