<?php

/**
 * BaseMailTemplates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $text
 * @property string $subject
 * @property string $slug
 * 
 * @method clob          getText()    Returns the current record's "text" value
 * @method string        getSubject() Returns the current record's "subject" value
 * @method string        getSlug()    Returns the current record's "slug" value
 * @method MailTemplates setText()    Sets the current record's "text" value
 * @method MailTemplates setSubject() Sets the current record's "subject" value
 * @method MailTemplates setSlug()    Sets the current record's "slug" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailTemplates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail_templates');
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}