<?php

/**
 * BaseVacancy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $content
 * @property boolean $is_public
 * 
 * @method string  getName()      Returns the current record's "name" value
 * @method clob    getContent()   Returns the current record's "content" value
 * @method boolean getIsPublic()  Returns the current record's "is_public" value
 * @method Vacancy setName()      Sets the current record's "name" value
 * @method Vacancy setContent()   Sets the current record's "content" value
 * @method Vacancy setIsPublic()  Sets the current record's "is_public" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVacancy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vacancy');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}