<?php

/**
 * BaseQiwi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $town
 * @property string $citygroup
 * @property string $addr
 * @property string $latitude
 * @property string $longitude
 * @property clob $descr
 * @property string $oh
 * @property integer $city_id
 * @property City $City
 * 
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getTown()      Returns the current record's "town" value
 * @method string  getCitygroup() Returns the current record's "citygroup" value
 * @method string  getAddr()      Returns the current record's "addr" value
 * @method string  getLatitude()  Returns the current record's "latitude" value
 * @method string  getLongitude() Returns the current record's "longitude" value
 * @method clob    getDescr()     Returns the current record's "descr" value
 * @method string  getOh()        Returns the current record's "oh" value
 * @method integer getCityId()    Returns the current record's "city_id" value
 * @method City    getCity()      Returns the current record's "City" value
 * @method Qiwi    setName()      Sets the current record's "name" value
 * @method Qiwi    setTown()      Sets the current record's "town" value
 * @method Qiwi    setCitygroup() Sets the current record's "citygroup" value
 * @method Qiwi    setAddr()      Sets the current record's "addr" value
 * @method Qiwi    setLatitude()  Sets the current record's "latitude" value
 * @method Qiwi    setLongitude() Sets the current record's "longitude" value
 * @method Qiwi    setDescr()     Sets the current record's "descr" value
 * @method Qiwi    setOh()        Sets the current record's "oh" value
 * @method Qiwi    setCityId()    Sets the current record's "city_id" value
 * @method Qiwi    setCity()      Sets the current record's "City" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQiwi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qiwi');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('town', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('citygroup', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('addr', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('latitude', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('longitude', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descr', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('oh', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}