<?php

/**
 * BaseCollection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subid
 * @property string $name
 * @property clob $content
 * @property boolean $is_public
 * @property boolean $is_popular
 * @property clob $priority_sort_list
 * @property string $title
 * @property string $keywords
 * @property string $description
 * @property string $image
 * 
 * @method integer    getSubid()              Returns the current record's "subid" value
 * @method string     getName()               Returns the current record's "name" value
 * @method clob       getContent()            Returns the current record's "content" value
 * @method boolean    getIsPublic()           Returns the current record's "is_public" value
 * @method boolean    getIsPopular()          Returns the current record's "is_popular" value
 * @method clob       getPrioritySortList()   Returns the current record's "priority_sort_list" value
 * @method string     getTitle()              Returns the current record's "title" value
 * @method string     getKeywords()           Returns the current record's "keywords" value
 * @method string     getDescription()        Returns the current record's "description" value
 * @method string     getImage()              Returns the current record's "image" value
 * @method Collection setSubid()              Sets the current record's "subid" value
 * @method Collection setName()               Sets the current record's "name" value
 * @method Collection setContent()            Sets the current record's "content" value
 * @method Collection setIsPublic()           Sets the current record's "is_public" value
 * @method Collection setIsPopular()          Sets the current record's "is_popular" value
 * @method Collection setPrioritySortList()   Sets the current record's "priority_sort_list" value
 * @method Collection setTitle()              Sets the current record's "title" value
 * @method Collection setKeywords()           Sets the current record's "keywords" value
 * @method Collection setDescription()        Sets the current record's "description" value
 * @method Collection setImage()              Sets the current record's "image" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collection');
        $this->hasColumn('subid', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_popular', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('priority_sort_list', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => false,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($sluggable0);
    }
}