<?php

/**
 * BaseProductActionLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $prodid
 * @property string $manid
 * @property string $count
 * @property string $discount
 * @property string $endaction
 * @property string $step
 * 
 * @method string           getProdid()    Returns the current record's "prodid" value
 * @method string           getManid()     Returns the current record's "manid" value
 * @method string           getCount()     Returns the current record's "count" value
 * @method string           getDiscount()  Returns the current record's "discount" value
 * @method string           getEndaction() Returns the current record's "endaction" value
 * @method string           getStep()      Returns the current record's "step" value
 * @method ProductActionLog setProdid()    Sets the current record's "prodid" value
 * @method ProductActionLog setManid()     Sets the current record's "manid" value
 * @method ProductActionLog setCount()     Sets the current record's "count" value
 * @method ProductActionLog setDiscount()  Sets the current record's "discount" value
 * @method ProductActionLog setEndaction() Sets the current record's "endaction" value
 * @method ProductActionLog setStep()      Sets the current record's "step" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductActionLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_action_log');
        $this->hasColumn('prodid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('manid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('count', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('discount', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('endaction', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('step', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}