<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $precontent
 * @property clob $content
 * @property boolean $is_public
 * @property string $photo_url
 * @property Doctrine_Collection $NewsPages
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method clob                getPrecontent() Returns the current record's "precontent" value
 * @method clob                getContent()    Returns the current record's "content" value
 * @method boolean             getIsPublic()   Returns the current record's "is_public" value
 * @method string              getPhotoUrl()   Returns the current record's "photo_url" value
 * @method Doctrine_Collection getNewsPages()  Returns the current record's "NewsPages" collection
 * @method News                setName()       Sets the current record's "name" value
 * @method News                setPrecontent() Sets the current record's "precontent" value
 * @method News                setContent()    Sets the current record's "content" value
 * @method News                setIsPublic()   Sets the current record's "is_public" value
 * @method News                setPhotoUrl()   Sets the current record's "photo_url" value
 * @method News                setNewsPages()  Sets the current record's "NewsPages" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('precontent', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('photo_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Page as NewsPages', array(
             'refClass' => 'NewsPage',
             'local' => 'news_id',
             'foreign' => 'page_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => false,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}