<?php

/**
 * BaseCardsmobile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $barcode
 * @property integer $user_id
 * @property boolean $is_public
 * @property string $phone
 * @property string $city
 * @property string $country
 * @property string $email
 * @property string $sex
 * @property string $user_name
 * @property string $user_family
 * @property string $user_subname
 * @property boolean $is_reserved
 * @property date $birthday
 * @property boolean $is_allow_email
 * @property boolean $is_allow_sms
 * @property boolean $is_allow_call
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string      getBarcode()        Returns the current record's "barcode" value
 * @method integer     getUserId()         Returns the current record's "user_id" value
 * @method boolean     getIsPublic()       Returns the current record's "is_public" value
 * @method string      getPhone()          Returns the current record's "phone" value
 * @method string      getCity()           Returns the current record's "city" value
 * @method string      getCountry()        Returns the current record's "country" value
 * @method string      getEmail()          Returns the current record's "email" value
 * @method string      getSex()            Returns the current record's "sex" value
 * @method string      getUserName()       Returns the current record's "user_name" value
 * @method string      getUserFamily()     Returns the current record's "user_family" value
 * @method string      getUserSubname()    Returns the current record's "user_subname" value
 * @method boolean     getIsReserved()     Returns the current record's "is_reserved" value
 * @method date        getBirthday()       Returns the current record's "birthday" value
 * @method boolean     getIsAllowEmail()   Returns the current record's "is_allow_email" value
 * @method boolean     getIsAllowSms()     Returns the current record's "is_allow_sms" value
 * @method boolean     getIsAllowCall()    Returns the current record's "is_allow_call" value
 * @method sfGuardUser getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method Cardsmobile setBarcode()        Sets the current record's "barcode" value
 * @method Cardsmobile setUserId()         Sets the current record's "user_id" value
 * @method Cardsmobile setIsPublic()       Sets the current record's "is_public" value
 * @method Cardsmobile setPhone()          Sets the current record's "phone" value
 * @method Cardsmobile setCity()           Sets the current record's "city" value
 * @method Cardsmobile setCountry()        Sets the current record's "country" value
 * @method Cardsmobile setEmail()          Sets the current record's "email" value
 * @method Cardsmobile setSex()            Sets the current record's "sex" value
 * @method Cardsmobile setUserName()       Sets the current record's "user_name" value
 * @method Cardsmobile setUserFamily()     Sets the current record's "user_family" value
 * @method Cardsmobile setUserSubname()    Sets the current record's "user_subname" value
 * @method Cardsmobile setIsReserved()     Sets the current record's "is_reserved" value
 * @method Cardsmobile setBirthday()       Sets the current record's "birthday" value
 * @method Cardsmobile setIsAllowEmail()   Sets the current record's "is_allow_email" value
 * @method Cardsmobile setIsAllowSms()     Sets the current record's "is_allow_sms" value
 * @method Cardsmobile setIsAllowCall()    Sets the current record's "is_allow_call" value
 * @method Cardsmobile setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCardsmobile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cardsmobile');
        $this->hasColumn('barcode', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('phone', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_family', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_subname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_reserved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('is_allow_email', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_allow_sms', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_allow_call', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}