<?php

/**
 * BaseMailsendlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $comment
 * 
 * @method clob        getComment() Returns the current record's "comment" value
 * @method Mailsendlog setComment() Sets the current record's "comment" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailsendlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailsendlog');
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}