<?php

/**
 * BaseFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property clob $precontent
 * @property clob $content
 * @property boolean $is_public
 * @property string $img
 * @property string $img_preview
 * @property integer $views_count
 * @property boolean $is_related
 * @property integer $positionrelated
 * @property string $title
 * @property string $keywords
 * @property string $description
 * @property string $category_slug
 * @property Doctrine_Collection $Faqcategory
 * @property Doctrine_Collection $CategoryFaq
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getSlug()            Returns the current record's "slug" value
 * @method clob                getPrecontent()      Returns the current record's "precontent" value
 * @method clob                getContent()         Returns the current record's "content" value
 * @method boolean             getIsPublic()        Returns the current record's "is_public" value
 * @method string              getImg()             Returns the current record's "img" value
 * @method string              getImgPreview()      Returns the current record's "img_preview" value
 * @method integer             getViewsCount()      Returns the current record's "views_count" value
 * @method boolean             getIsRelated()       Returns the current record's "is_related" value
 * @method integer             getPositionrelated() Returns the current record's "positionrelated" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getKeywords()        Returns the current record's "keywords" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method string              getCategorySlug()    Returns the current record's "category_slug" value
 * @method Doctrine_Collection getFaqcategory()     Returns the current record's "Faqcategory" collection
 * @method Doctrine_Collection getCategoryFaq()     Returns the current record's "CategoryFaq" collection
 * @method Faq                 setName()            Sets the current record's "name" value
 * @method Faq                 setSlug()            Sets the current record's "slug" value
 * @method Faq                 setPrecontent()      Sets the current record's "precontent" value
 * @method Faq                 setContent()         Sets the current record's "content" value
 * @method Faq                 setIsPublic()        Sets the current record's "is_public" value
 * @method Faq                 setImg()             Sets the current record's "img" value
 * @method Faq                 setImgPreview()      Sets the current record's "img_preview" value
 * @method Faq                 setViewsCount()      Sets the current record's "views_count" value
 * @method Faq                 setIsRelated()       Sets the current record's "is_related" value
 * @method Faq                 setPositionrelated() Sets the current record's "positionrelated" value
 * @method Faq                 setTitle()           Sets the current record's "title" value
 * @method Faq                 setKeywords()        Sets the current record's "keywords" value
 * @method Faq                 setDescription()     Sets the current record's "description" value
 * @method Faq                 setCategorySlug()    Sets the current record's "category_slug" value
 * @method Faq                 setFaqcategory()     Sets the current record's "Faqcategory" collection
 * @method Faq                 setCategoryFaq()     Sets the current record's "CategoryFaq" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('precontent', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img_preview', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('views_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_related', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('positionrelated', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Faqcategory', array(
             'refClass' => 'CategoryFaq',
             'local' => 'faq_id',
             'foreign' => 'faqcategory_id'));

        $this->hasMany('CategoryFaq', array(
             'local' => 'id',
             'foreign' => 'faq_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => false,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($sortable0);
    }
}