<?php

/**
 * BaseRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $outurl
 * @property string $inurl
 * 
 * @method string   getOuturl() Returns the current record's "outurl" value
 * @method string   getInurl()  Returns the current record's "inurl" value
 * @method Redirect setOuturl() Sets the current record's "outurl" value
 * @method Redirect setInurl()  Sets the current record's "inurl" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRedirect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('redirect');
        $this->hasColumn('outurl', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('inurl', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}