<?php

/**
 * BaseDopInfoProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dop_info_id
 * @property integer $product_id
 * @property string $code
 * @property DopInfo $DopInfo
 * @property Product $Product
 * 
 * @method integer        getDopInfoId()   Returns the current record's "dop_info_id" value
 * @method integer        getProductId()   Returns the current record's "product_id" value
 * @method string         getCode()        Returns the current record's "code" value
 * @method DopInfo        getDopInfo()     Returns the current record's "DopInfo" value
 * @method Product        getProduct()     Returns the current record's "Product" value
 * @method DopInfoProduct setDopInfoId()   Sets the current record's "dop_info_id" value
 * @method DopInfoProduct setProductId()   Sets the current record's "product_id" value
 * @method DopInfoProduct setCode()        Sets the current record's "code" value
 * @method DopInfoProduct setDopInfo()     Sets the current record's "DopInfo" value
 * @method DopInfoProduct setProduct()     Sets the current record's "Product" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDopInfoProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dop_info_product');
        $this->hasColumn('dop_info_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DopInfo', array(
             'local' => 'dop_info_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}