<?php

/**
 * BaseQrRedirects
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $shop
 * @property integer $shop_id
 * @property enum $type
 * @property Shops $Shops
 * 
 * @method string      getShop()    Returns the current record's "shop" value
 * @method integer     getShopId()  Returns the current record's "shop_id" value
 * @method enum        getType()    Returns the current record's "type" value
 * @method Shops       getShops()   Returns the current record's "Shops" value
 * @method QrRedirects setShop()    Sets the current record's "shop" value
 * @method QrRedirects setShopId()  Sets the current record's "shop_id" value
 * @method QrRedirects setType()    Sets the current record's "type" value
 * @method QrRedirects setShops()   Sets the current record's "Shops" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQrRedirects extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qr_redirects');
        $this->hasColumn('shop', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('shop_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '2gis',
              1 => 'google',
              2 => 'yandex',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Shops', array(
             'local' => 'shop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}