<?php

/**
 * BaseProductPhotoalbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $photoalbum_id
 * @property Product $Product
 * @property Photoalbum $Photoalbum
 * 
 * @method integer           getProductId()     Returns the current record's "product_id" value
 * @method integer           getPhotoalbumId()  Returns the current record's "photoalbum_id" value
 * @method Product           getProduct()       Returns the current record's "Product" value
 * @method Photoalbum        getPhotoalbum()    Returns the current record's "Photoalbum" value
 * @method ProductPhotoalbum setProductId()     Sets the current record's "product_id" value
 * @method ProductPhotoalbum setPhotoalbumId()  Sets the current record's "photoalbum_id" value
 * @method ProductPhotoalbum setProduct()       Sets the current record's "Product" value
 * @method ProductPhotoalbum setPhotoalbum()    Sets the current record's "Photoalbum" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductPhotoalbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_photoalbum');
        $this->hasColumn('product_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('photoalbum_id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Photoalbum', array(
             'local' => 'photoalbum_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}