<?php

/**
 * BaseArticlelink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $words
 * @property string $link
 * 
 * @method string      getWords() Returns the current record's "words" value
 * @method string      getLink()  Returns the current record's "link" value
 * @method Articlelink setWords() Sets the current record's "words" value
 * @method Articlelink setLink()  Sets the current record's "link" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticlelink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('articlelink');
        $this->hasColumn('words', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}