<?php

/**
 * BaseActionsDiscountInterval
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $actionsdiscount_id
 * @property integer $start
 * @property integer $end
 * @property integer $discount
 * @property ActionsDiscount $ActionsDiscount
 * 
 * @method integer                 getActionsdiscountId()  Returns the current record's "actionsdiscount_id" value
 * @method integer                 getStart()              Returns the current record's "start" value
 * @method integer                 getEnd()                Returns the current record's "end" value
 * @method integer                 getDiscount()           Returns the current record's "discount" value
 * @method ActionsDiscount         getActionsDiscount()    Returns the current record's "ActionsDiscount" value
 * @method ActionsDiscountInterval setActionsdiscountId()  Sets the current record's "actionsdiscount_id" value
 * @method ActionsDiscountInterval setStart()              Sets the current record's "start" value
 * @method ActionsDiscountInterval setEnd()                Sets the current record's "end" value
 * @method ActionsDiscountInterval setDiscount()           Sets the current record's "discount" value
 * @method ActionsDiscountInterval setActionsDiscount()    Sets the current record's "ActionsDiscount" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActionsDiscountInterval extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actions_discount_interval');
        $this->hasColumn('actionsdiscount_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('discount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActionsDiscount', array(
             'local' => 'actionsdiscount_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}