<?php

/**
 * BaseOprosnik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $orderid
 * @property clob $dataans
 * @property integer $rating
 * @property enum $shop
 * 
 * @method string   getOrderid() Returns the current record's "orderid" value
 * @method clob     getDataans() Returns the current record's "dataans" value
 * @method integer  getRating()  Returns the current record's "rating" value
 * @method enum     getShop()    Returns the current record's "shop" value
 * @method Oprosnik setOrderid() Sets the current record's "orderid" value
 * @method Oprosnik setDataans() Sets the current record's "dataans" value
 * @method Oprosnik setRating()  Sets the current record's "rating" value
 * @method Oprosnik setShop()    Sets the current record's "shop" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOprosnik extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oprosnik');
        $this->hasColumn('orderid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dataans', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('shop', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Магазин',
              1 => 'Интернет магазин',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}