<?php

/**
 * BaseCategoryProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $product_id
 * @property Category $Category
 * @property Product $Product
 * 
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method integer         getProductId()   Returns the current record's "product_id" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method Product         getProduct()     Returns the current record's "Product" value
 * @method CategoryProduct setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryProduct setProductId()   Sets the current record's "product_id" value
 * @method CategoryProduct setCategory()    Sets the current record's "Category" value
 * @method CategoryProduct setProduct()     Sets the current record's "Product" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_product');
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}