<?php

/**
 * BaseVacancyReply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property integer $vacancy_id
 * @property string $vacancy_name
 * 
 * @method string       getName()         Returns the current record's "name" value
 * @method string       getEmail()        Returns the current record's "email" value
 * @method string       getPhone()        Returns the current record's "phone" value
 * @method integer      getVacancyId()    Returns the current record's "vacancy_id" value
 * @method string       getVacancyName()  Returns the current record's "vacancy_name" value
 * @method VacancyReply setName()         Sets the current record's "name" value
 * @method VacancyReply setEmail()        Sets the current record's "email" value
 * @method VacancyReply setPhone()        Sets the current record's "phone" value
 * @method VacancyReply setVacancyId()    Sets the current record's "vacancy_id" value
 * @method VacancyReply setVacancyName()  Sets the current record's "vacancy_name" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVacancyReply extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vacancy_reply');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('vacancy_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('vacancy_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}