<?php

/**
 * BaseTests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property clob $content
 * @property boolean $is_public
 * @property string $img
 * @property integer $views_count
 * @property integer $votes_count
 * @property integer $rating
 * @property integer $writing
 * @property string $title
 * @property string $keywords
 * @property string $description
 * @property Doctrine_Collection $Question
 * @property Doctrine_Collection $Result
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getSlug()        Returns the current record's "slug" value
 * @method clob                getContent()     Returns the current record's "content" value
 * @method boolean             getIsPublic()    Returns the current record's "is_public" value
 * @method string              getImg()         Returns the current record's "img" value
 * @method integer             getViewsCount()  Returns the current record's "views_count" value
 * @method integer             getVotesCount()  Returns the current record's "votes_count" value
 * @method integer             getRating()      Returns the current record's "rating" value
 * @method integer             getWriting()     Returns the current record's "writing" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getKeywords()    Returns the current record's "keywords" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getQuestion()    Returns the current record's "Question" collection
 * @method Doctrine_Collection getResult()      Returns the current record's "Result" collection
 * @method Tests               setName()        Sets the current record's "name" value
 * @method Tests               setSlug()        Sets the current record's "slug" value
 * @method Tests               setContent()     Sets the current record's "content" value
 * @method Tests               setIsPublic()    Sets the current record's "is_public" value
 * @method Tests               setImg()         Sets the current record's "img" value
 * @method Tests               setViewsCount()  Sets the current record's "views_count" value
 * @method Tests               setVotesCount()  Sets the current record's "votes_count" value
 * @method Tests               setRating()      Sets the current record's "rating" value
 * @method Tests               setWriting()     Sets the current record's "writing" value
 * @method Tests               setTitle()       Sets the current record's "title" value
 * @method Tests               setKeywords()    Sets the current record's "keywords" value
 * @method Tests               setDescription() Sets the current record's "description" value
 * @method Tests               setQuestion()    Sets the current record's "Question" collection
 * @method Tests               setResult()      Sets the current record's "Result" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTests extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tests');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('views_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('votes_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('writing', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TestsQuestion as Question', array(
             'local' => 'id',
             'foreign' => 'test_id'));

        $this->hasMany('TestsResult as Result', array(
             'local' => 'id',
             'foreign' => 'test_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => false,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}