<?php

/**
 * BaseSearchLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text
 * 
 * @method string    getText() Returns the current record's "text" value
 * @method SearchLog setText() Sets the current record's "text" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSearchLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('search_log');
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}