<?php

/**
 * BaseDopInfoCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $namecompare
 * @property boolean $is_compare
 * @property boolean $is_public
 * @property Doctrine_Collection $Category
 * @property Doctrine_Collection $DopInfoCategory
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getNamecompare()                 Returns the current record's "namecompare" value
 * @method boolean             getIsCompare()                   Returns the current record's "is_compare" value
 * @method boolean             getIsPublic()                    Returns the current record's "is_public" value
 * @method Doctrine_Collection getCategory()                    Returns the current record's "Category" collection
 * @method Doctrine_Collection getDopInfoCategoryFullCategory() Returns the current record's "DopInfoCategoryFullCategory" collection
 * @method Doctrine_Collection getDopInfoCategory()             Returns the current record's "DopInfoCategory" collection
 * @method DopInfoCategory     setName()                        Sets the current record's "name" value
 * @method DopInfoCategory     setNamecompare()                 Sets the current record's "namecompare" value
 * @method DopInfoCategory     setIsCompare()                   Sets the current record's "is_compare" value
 * @method DopInfoCategory     setIsPublic()                    Sets the current record's "is_public" value
 * @method DopInfoCategory     setCategory()                    Sets the current record's "Category" collection
 * @method DopInfoCategory     setDopInfoCategoryFullCategory() Sets the current record's "DopInfoCategoryFullCategory" collection
 * @method DopInfoCategory     setDopInfoCategory()             Sets the current record's "DopInfoCategory" collectionFullCategory
 * @property Doctrine_Collection $DopInfoCategory
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getNamecompare()                 Returns the current record's "namecompare" value
 * @method boolean             getIsCompare()                   Returns the current record's "is_compare" value
 * @method boolean             getIsPublic()                    Returns the current record's "is_public" value
 * @method Doctrine_Collection getCategory()                    Returns the current record's "Category" collection
 * @method Doctrine_Collection getDopInfoCategoryFullCategory() Returns the current record's "DopInfoCategoryFullCategory" collection
 * @method Doctrine_Collection getDopInfoCategory()             Returns the current record's "DopInfoCategory" collection
 * @method DopInfoCategory     setName()                        Sets the current record's "name" value
 * @method DopInfoCategory     setNamecompare()                 Sets the current record's "namecompare" value
 * @method DopInfoCategory     setIsCompare()                   Sets the current record's "is_compare" value
 * @method DopInfoCategory     setIsPublic()                    Sets the current record's "is_public" value
 * @method DopInfoCategory     setCategory()                    Sets the current record's "Category" collection
 * @method DopInfoCategory     setDopInfoCategoryFullCategory() Sets the current record's "DopInfoCategoryFullCategory" collection
 * @method DopInfoCategory     setDopInfoCategory()             Sets the current record's "DopInfoCategory" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDopInfoCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dop_info_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('namecompare', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_compare', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DopInfoCategoryFull as Category', array(
             'refClass' => 'DopInfoCategoryFullCategory',
             'local' => 'dop_info_category_id',
             'foreign' => 'dop_info_category_full_id'));

        $this->hasMany('DopInfoCategoryFullCategory', array(
             'local' => 'id',
             'foreign' => 'dop_info_category_id'));

        $this->hasMany('DopInfo as DopInfoCategory', array(
             'local' => 'id',
             'foreign' => 'dicategory_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}