<?php

/**
 * BaseSorttablerelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property Product $Product
 * 
 * @method integer          getProductId()  Returns the current record's "product_id" value
 * @method Product          getProduct()    Returns the current record's "Product" value
 * @method Sorttablerelated setProductId()  Sets the current record's "product_id" value
 * @method Sorttablerelated setProduct()    Sets the current record's "Product" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSorttablerelated extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sorttablerelated');
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}