<?php

/**
 * BaseLogs404
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $urlFrom
 * @property string $ip
 * 
 * @method string  getUrl()     Returns the current record's "url" value
 * @method string  getUrlFrom() Returns the current record's "urlFrom" value
 * @method string  getIp()      Returns the current record's "ip" value
 * @method Logs404 setUrl()     Sets the current record's "url" value
 * @method Logs404 setUrlFrom() Sets the current record's "urlFrom" value
 * @method Logs404 setIp()      Sets the current record's "ip" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogs404 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logs404');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('urlFrom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}