generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Photo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        filename:
          label: Фотография
        name:
          label: Имя
        is_public:
          label: Доступна
        album_id:
          label: Альбом
        photo:
          label: Изображение
      list:    
        title: Фотографии
        display: [ name, _photo, is_public ]
      filter:  
        display: [ name, is_public, album_id ]
      form:            
        display: 
          Основная информация: [ name, filename, is_public, album_id ]
      edit:    
        title: Редактирование фотографии "%%name%%"
      new:     
        title: Создание фотографии
