<?php

/**
 * ActionsDiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionsDiscountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionsDiscountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionsDiscount');
    }
}