<?php

/**
 * ActionsDiscountIntervalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionsDiscountIntervalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionsDiscountIntervalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionsDiscountInterval');
    }
}