<?php

/**
 * ArticlecategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticlecategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticlecategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Articlecategory');
    }
}