<?php

/**
 * BannersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banners');
    }
}