<?php

/**
 * BonusMailsendLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonusMailsendLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BonusMailsendLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BonusMailsendLog');
    }
}