<?php

/**
 * BottombannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BottombannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BottombannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bottombanner');
    }
}