<?php

/**
 * CaptchaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CaptchaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CaptchaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Captcha');
    }
}