<?php

/**
 * CardsmobileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CardsmobileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CardsmobileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cardsmobile');
    }
}