<?php

/**
 * CategoryArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryArticle');
    }
}