<?php

/**
 * CategoryCatalogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryCatalogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryCatalogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryCatalog');
    }
}