<?php

/**
 * CategorypageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategorypageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategorypageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categorypage');
    }
}