<?php

/**
 * CategoryarticleCatalogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryarticleCatalogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryarticleCatalogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryarticleCatalog');
    }
}