<?php

/**
 * CategorypagePageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategorypagePageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategorypagePageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategorypagePage');
    }
}