<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Magazin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory {

    public function getNameSubCategory() {
        $name = ($this->getParentsId()) ? " ---- " : "";
        return $name . $this->getName();
    }

    public function setUp() {
        parent::setUp();

        $this->hasMany('Category as Children', array(
            'orderBy' => 'position ASC',
            'local' => 'id',
            'foreign' => 'parents_id'));
    }

}
