<?php

/**
 * CompareTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompareTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compare');
    }
}