<?php

/**
 * CouponsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CouponsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CouponsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coupons');
    }
}