<?php

/**
 * DeliveryPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeliveryPayment');
    }
}