<?php

/**
 * Delivery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Magazin
 * @subpackage model
 * @author     Belfegor
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Delivery extends BaseDelivery
{
}
