<?php

/**
 * DopInfoProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopInfoProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopInfoProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DopInfoProduct');
    }
}