<?php

/**
 * DopInfoCategoryFullCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopInfoCategoryFullCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopInfoCategoryFullCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DopInfoCategoryFullCategory');
    }
}