<?php

/**
 * DopInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Magazin
 * @subpackage model
 * @author     Belfegor
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DopInfo extends BaseDopInfo {

    public function getNameValue() {
        return $this->getName() . " - " . $this->getValue();
    }

    public function getCategoryValue() {
        //print_r(array_keys($this));
        //print_r($this->exportTo("array"));
        return $this->getDopInfoCategory()->getName() . " - " . $this->getValue();
    }

}
