<?php

/**
 * DopInfoCategoryFullDopInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopInfoCategoryFullDopInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopInfoCategoryFullDopInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DopInfoCategoryFullDopInfo');
    }
}