<?php

/**
 * ExpertsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpertsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpertsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Experts');
    }
}