<?php

/**
 * FastOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FastOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FastOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FastOrder');
    }
}