<?php

/**
 * FastOrderLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FastOrderLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FastOrderLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FastOrderLog');
    }
}