<?php

/**
 * HoroscopeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoroscopeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoroscopeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Horoscope');
    }
}