<?php

/**
 * HoroscopesovmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoroscopesovmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoroscopesovmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Horoscopesovm');
    }
}