<?php

/**
 * ImlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Iml');
    }
}