<?php

/**
 * Logs404Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Logs404Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Logs404Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logs404');
    }
}