<?php

/**
 * MailchangestatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailchangestatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailchangestatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailchangestatus');
    }
}