<?php

/**
 * NotificationCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificationCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotificationCategory');
    }
}