<?php

/**
 * OprosnikTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OprosnikTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OprosnikTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Oprosnik');
    }
}