<?php

/**
 * OrdersShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdersShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdersShop');
    }
}