<?php

/**
 * OrdersPaymentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersPaymentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdersPaymentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdersPayments');
    }
}