<?php

/**
 * PartnerIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnerIdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnerIdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PartnerId');
    }
}