<?php

/**
 * PaymentdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentdocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paymentdoc');
    }
}