<?php

/**
 * PhotoalbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoalbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoalbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photoalbum');
    }
}