<?php

/**
 * ProductPhotoalbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPhotoalbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPhotoalbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPhotoalbum');
    }
}