<?php

/**
 * ProductForBackUpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductForBackUpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductForBackUpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductForBackUp');
    }
}