<?php

/**
 * ProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Product');
    }

    public static function getRelatedProduct() {
        $query = self::getInstance()
                ->createQuery('p')
                ->where('p.is_related = true')
                ->orderBy('rand()');

        return $query->execute();
    }
    public function getFilterList() {
      return Doctrine_Query::create()
          ->select('p.id, p.name')
          ->from('product p, comments c')
          ->where('c.product_id = p.id')
          ->groupBy('p.id')
          ->execute();
    }

    public static function getManagers() {
        $query = sfGuardUserTable::getInstance()
                ->createQuery('u')
                ->where('u.id in (SELECT user_id
FROM  `sf_guard_user_permission`
WHERE  `permission_id` =8)');

        return $query->execute();
    }

}
