<?php

/**
 * ProductActionLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductActionLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductActionLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductActionLog');
    }
}