<?php

/**
 * QiwiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QiwiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QiwiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Qiwi');
    }
}