<?php

/**
 * RedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Redirect');
    }
}