<?php

/**
 * RussianPostCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RussianPostCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RussianPostCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RussianPostCity');
    }
}