<?php

/**
 * SenduserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SenduserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SenduserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Senduser');
    }
}