<?php

/**
 * ServicerequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicerequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicerequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servicerequest');
    }
}