<?php

/**
 * ShopsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Shops');
    }
}