<?php

/**
 * SmsProofTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsProofTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsProofTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsProof');
    }
}