<?php

/**
 * SorttablerelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SorttablerelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SorttablerelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sorttablerelated');
    }
}