<?php

/**
 * SynonymsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SynonymsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SynonymsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Synonyms');
    }
}