<?php

/**
 * TestsQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestsQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestsQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestsQuestion');
    }
}