<?php

/**
 * TestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tests');
    }
}