<?php

/**
 * TestsQuestionAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestsQuestionAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestsQuestionAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestsQuestionAnswer');
    }
}