<?php

/**
 * VacancyReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VacancyReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VacancyReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VacancyReply');
    }
}