<?php

/**
 * VacancyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VacancyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VacancyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vacancy');
    }
}