<?php

/**
 * Validw3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Validw3Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Validw3Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Validw3');
    }
}