<?php

/**
 * WheelsectorsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WheelsectorsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WheelsectorsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wheelsectors');
    }
}