generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Articlelink
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          articlelink
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        words:
          label: Слово
        link:
          label: Ссылка
        count:
          label: Количество ссылок в статьях
      list:    
        title: Ссылки в статьях
        display: [ words, link, _count ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
