<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property date $birthday
 * @property string $phone
 * @property string $index_house
 * @property string $city
 * @property string $region_fias_id
 * @property string $street
 * @property string $house
 * @property string $korpus
 * @property string $apartament
 * @property string $sex
 * @property string $ssidentity
 * @property string $oldphone
 * @property boolean $activephone
 * @property integer $activephonecode
 * @property string $last_ip
 * @property clob $personal_recomendation
 * @property clob $cart
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $User
 * 
 * @method string                getFirstName()              Returns the current record's "first_name" value
 * @method string                getLastName()               Returns the current record's "last_name" value
 * @method string                getEmailAddress()           Returns the current record's "email_address" value
 * @method string                getUsername()               Returns the current record's "username" value
 * @method string                getAlgorithm()              Returns the current record's "algorithm" value
 * @method string                getSalt()                   Returns the current record's "salt" value
 * @method string                getPassword()               Returns the current record's "password" value
 * @method boolean               getIsActive()               Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()           Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()              Returns the current record's "last_login" value
 * @method date                  getBirthday()               Returns the current record's "birthday" value
 * @method string                getPhone()                  Returns the current record's "phone" value
 * @method string                getIndexHouse()             Returns the current record's "index_house" value
 * @method string                getCity()                   Returns the current record's "city" value
 * @method string                getRegionFiasId()           Returns the current record's "region_fias_id" value
 * @method string                getStreet()                 Returns the current record's "street" value
 * @method string                getHouse()                  Returns the current record's "house" value
 * @method string                getKorpus()                 Returns the current record's "korpus" value
 * @method string                getApartament()             Returns the current record's "apartament" value
 * @method string                getSex()                    Returns the current record's "sex" value
 * @method string                getSsidentity()             Returns the current record's "ssidentity" value
 * @method string                getOldphone()               Returns the current record's "oldphone" value
 * @method boolean               getActivephone()            Returns the current record's "activephone" value
 * @method integer               getActivephonecode()        Returns the current record's "activephonecode" value
 * @method string                getLastIp()                 Returns the current record's "last_ip" value
 * @method clob                  getPersonalRecomendation()  Returns the current record's "personal_recomendation" value
 * @method clob                  getCart()                   Returns the current record's "cart" value
 * @method Doctrine_Collection   getGroups()                 Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()            Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getSfGuardUserPermission()  Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()       Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()           Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()         Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getUser()                   Returns the current record's "User" collection
 * @method sfGuardUser           setFirstName()              Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()               Sets the current record's "last_name" value
 * @method sfGuardUser           setEmailAddress()           Sets the current record's "email_address" value
 * @method sfGuardUser           setUsername()               Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()              Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                   Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()               Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()               Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()           Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()              Sets the current record's "last_login" value
 * @method sfGuardUser           setBirthday()               Sets the current record's "birthday" value
 * @method sfGuardUser           setPhone()                  Sets the current record's "phone" value
 * @method sfGuardUser           setIndexHouse()             Sets the current record's "index_house" value
 * @method sfGuardUser           setCity()                   Sets the current record's "city" value
 * @method sfGuardUser           setRegionFiasId()           Sets the current record's "region_fias_id" value
 * @method sfGuardUser           setStreet()                 Sets the current record's "street" value
 * @method sfGuardUser           setHouse()                  Sets the current record's "house" value
 * @method sfGuardUser           setKorpus()                 Sets the current record's "korpus" value
 * @method sfGuardUser           setApartament()             Sets the current record's "apartament" value
 * @method sfGuardUser           setSex()                    Sets the current record's "sex" value
 * @method sfGuardUser           setSsidentity()             Sets the current record's "ssidentity" value
 * @method sfGuardUser           setOldphone()               Sets the current record's "oldphone" value
 * @method sfGuardUser           setActivephone()            Sets the current record's "activephone" value
 * @method sfGuardUser           setActivephonecode()        Sets the current record's "activephonecode" value
 * @method sfGuardUser           setLastIp()                 Sets the current record's "last_ip" value
 * @method sfGuardUser           setPersonalRecomendation()  Sets the current record's "personal_recomendation" value
 * @method sfGuardUser           setCart()                   Sets the current record's "cart" value
 * @method sfGuardUser           setGroups()                 Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()            Sets the current record's "Permissions" collection
 * @method sfGuardUser           setSfGuardUserPermission()  Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()       Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()           Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()         Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setUser()                   Sets the current record's "User" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('index_house', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('region_fias_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('house', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('korpus', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('apartament', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ssidentity', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('oldphone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('activephone', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('activephonecode', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('last_ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('personal_recomendation', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('cart', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Orders as User', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}