generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MailTemplates
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          mail_templates
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        text:
          label: Шаблон
        subject:
          label: Тема письма
        slug:
          label: Уникальный индефикатор
      list:   
        title: Шаблоны писем
        display: [ subject, slug ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
