generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Redirect
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          redirect
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        outurl:
          label: Куда
        inurl:
          label: Откуда
      list:    
        title: Редиректы
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
