generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Comments
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          comments
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:   
        text:
          label: Комментарий
        product_id:
          label: Товар
        article_id:
          label: Статья
        customer_id:
          label: Пользователь
        is_public:
          label: Доступен
        username:
          label: Имя
        mail:
          label: Почта
        page_id:
          label: ID страницы
        copy:
          label: Данные для копирования
        created_at:
            label: Дата создания
        answer:
            label: Ответ
        rate_set:
            label: Рейтинг
        comment_manager:
            label: Коментарий администратора
        point:
            label: Количесчтво баллов
      list:    
        title: Комментарии
        display: [ _product_id, _customer_id, username, text, _is_public, created_at, rate_set ]
      filter:  
        display: [ is_public ]
      form:    
        class: CommentsCPForm
        display: 
          Основная информация: [ product_id, article_id, page_id, username, mail, is_public, created_at, rate_set ]
          Комментарий: [ text,answer ]
          Модерация: [ comment_manager, point ]
      edit:    
        title: Редактирование комментария "%%id%%"
      new:     
        title: Создание комментария
