<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comments', 'username', 'string', '255', array(
             ));
        $this->addColumn('comments', 'mail', 'string', '255', array(
             ));
        $this->changeColumn('comments', 'customer_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('comments', 'username');
        $this->removeColumn('comments', 'mail');
    }
}
