<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('banners', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'href' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'alt' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'src' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_public' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'is_rotation' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('bonus', 'log', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->dropTable('banners');
        $this->removeColumn('bonus', 'log');
    }
}
