<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('photo', 'position', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('photo', 'position');
    }
}