<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('product', 'product_generalcategory_id_category_id', array(
             'name' => 'product_generalcategory_id_category_id',
             'local' => 'generalcategory_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->addIndex('product', 'product_generalcategory_id', array(
             'fields' => 
             array(
              0 => 'generalcategory_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('product', 'product_generalcategory_id_category_id');
        $this->removeIndex('product', 'product_generalcategory_id', array(
             'fields' => 
             array(
              0 => 'generalcategory_id',
             ),
             ));
    }
}