<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dop_info', 'dop_info_dicategory_id_dop_info_category_id', array(
             'name' => 'dop_info_dicategory_id_dop_info_category_id',
             'local' => 'dicategory_id',
             'foreign' => 'id',
             'foreignTable' => 'dop_info_category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('dop_info', 'dop_info_dicategory_id', array(
             'fields' => 
             array(
              0 => 'dicategory_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dop_info', 'dop_info_dicategory_id_dop_info_category_id');
        $this->removeIndex('dop_info', 'dop_info_dicategory_id', array(
             'fields' => 
             array(
              0 => 'dicategory_id',
             ),
             ));
    }
}