<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('product_photoalbum', 'product_photoalbum_product_id_product_id');
        $this->dropForeignKey('product_photoalbum', 'product_photoalbum_photoalbum_id_photoalbum_id');
        $this->createForeignKey('product_photoalbum', 'product_photoalbum_product_id_product_id_1', array(
             'name' => 'product_photoalbum_product_id_product_id_1',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product_photoalbum', 'product_photoalbum_photoalbum_id_photoalbum_id_1', array(
             'name' => 'product_photoalbum_photoalbum_id_photoalbum_id_1',
             'local' => 'photoalbum_id',
             'foreign' => 'id',
             'foreignTable' => 'photoalbum',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('product_photoalbum', 'product_photoalbum_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('product_photoalbum', 'product_photoalbum_photoalbum_id', array(
             'fields' => 
             array(
              0 => 'photoalbum_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('product_photoalbum', 'product_photoalbum_product_id_product_id', array(
             'name' => 'product_photoalbum_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('product_photoalbum', 'product_photoalbum_photoalbum_id_photoalbum_id', array(
             'name' => 'product_photoalbum_photoalbum_id_photoalbum_id',
             'local' => 'photoalbum_id',
             'foreign' => 'id',
             'foreignTable' => 'photoalbum',
             ));
        $this->dropForeignKey('product_photoalbum', 'product_photoalbum_product_id_product_id_1');
        $this->dropForeignKey('product_photoalbum', 'product_photoalbum_photoalbum_id_photoalbum_id_1');
        $this->removeIndex('product_photoalbum', 'product_photoalbum_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('product_photoalbum', 'product_photoalbum_photoalbum_id', array(
             'fields' => 
             array(
              0 => 'photoalbum_id',
             ),
             ));
    }
}