<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog', 'catalog_page_id_page_id', array(
             'name' => 'catalog_page_id_page_id',
             'local' => 'page_id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             ));
        $this->createForeignKey('category_catalog', 'category_catalog_category_id_category_id', array(
             'name' => 'category_catalog_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('category_catalog', 'category_catalog_catalog_id_catalog_id', array(
             'name' => 'category_catalog_catalog_id_catalog_id',
             'local' => 'catalog_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog', 'catalog_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
        $this->addIndex('category_catalog', 'category_catalog_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('category_catalog', 'category_catalog_catalog_id', array(
             'fields' => 
             array(
              0 => 'catalog_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog', 'catalog_page_id_page_id');
        $this->dropForeignKey('category_catalog', 'category_catalog_category_id_category_id');
        $this->dropForeignKey('category_catalog', 'category_catalog_catalog_id_catalog_id');
        $this->removeIndex('catalog', 'catalog_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
        $this->removeIndex('category_catalog', 'category_catalog_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('category_catalog', 'category_catalog_catalog_id', array(
             'fields' => 
             array(
              0 => 'catalog_id',
             ),
             ));
    }
}