<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog', 'description', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog', 'description');
    }
}