<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'step', 'enum', '', array(
             'values' => 
             array(
              0 => '1 сутки',
              1 => '2 суток',
              2 => '3 суток',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'step');
    }
}