<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('category_article', 'category_article_articlecategory_id_articlecategory_id', array(
             'name' => 'category_article_articlecategory_id_articlecategory_id',
             'local' => 'articlecategory_id',
             'foreign' => 'id',
             'foreignTable' => 'articlecategory',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('category_article', 'category_article_article_id_article_id', array(
             'name' => 'category_article_article_id_article_id',
             'local' => 'article_id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('categoryarticle_catalog', 'categoryarticle_catalog_articlecategory_id_articlecategory_id', array(
             'name' => 'categoryarticle_catalog_articlecategory_id_articlecategory_id',
             'local' => 'articlecategory_id',
             'foreign' => 'id',
             'foreignTable' => 'articlecategory',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('categoryarticle_catalog', 'categoryarticle_catalog_articlecatalog_id_articlecatalog_id', array(
             'name' => 'categoryarticle_catalog_articlecatalog_id_articlecatalog_id',
             'local' => 'articlecatalog_id',
             'foreign' => 'id',
             'foreignTable' => 'articlecatalog',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('category_article', 'category_article_articlecategory_id', array(
             'fields' => 
             array(
              0 => 'articlecategory_id',
             ),
             ));
        $this->addIndex('category_article', 'category_article_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
        $this->addIndex('categoryarticle_catalog', 'categoryarticle_catalog_articlecategory_id', array(
             'fields' => 
             array(
              0 => 'articlecategory_id',
             ),
             ));
        $this->addIndex('categoryarticle_catalog', 'categoryarticle_catalog_articlecatalog_id', array(
             'fields' => 
             array(
              0 => 'articlecatalog_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('category_article', 'category_article_articlecategory_id_articlecategory_id');
        $this->dropForeignKey('category_article', 'category_article_article_id_article_id');
        $this->dropForeignKey('categoryarticle_catalog', 'categoryarticle_catalog_articlecategory_id_articlecategory_id');
        $this->dropForeignKey('categoryarticle_catalog', 'categoryarticle_catalog_articlecatalog_id_articlecatalog_id');
        $this->removeIndex('category_article', 'category_article_articlecategory_id', array(
             'fields' => 
             array(
              0 => 'articlecategory_id',
             ),
             ));
        $this->removeIndex('category_article', 'category_article_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
        $this->removeIndex('categoryarticle_catalog', 'categoryarticle_catalog_articlecategory_id', array(
             'fields' => 
             array(
              0 => 'articlecategory_id',
             ),
             ));
        $this->removeIndex('categoryarticle_catalog', 'categoryarticle_catalog_articlecatalog_id', array(
             'fields' => 
             array(
              0 => 'articlecatalog_id',
             ),
             ));
    }
}