<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version48 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comments', 'comments_article_id_article_id', array(
             'name' => 'comments_article_id_article_id',
             'local' => 'article_id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('comments', 'comments_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comments', 'comments_article_id_article_id');
        $this->removeIndex('comments', 'comments_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
    }
}