<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comments', 'article_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('comments', 'article_id');
    }
}