<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('captcha', 'type', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('captcha', 'type');
    }
}