<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('article', 'tags', 'string', '255', array(
             ));
        $this->addColumn('article', 'title', 'string', '255', array(
             ));
        $this->addColumn('article', 'keywords', 'string', '255', array(
             ));
        $this->addColumn('article', 'description', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('article', 'tags');
        $this->removeColumn('article', 'title');
        $this->removeColumn('article', 'keywords');
        $this->removeColumn('article', 'description');
    }
}