<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('page', 'sitemaprate', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('page', 'sitemaprate');
    }
}