<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version72 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'prefix', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'prefix');
    }
}