<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version73 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog', 'tags', 'string', '255', array(
             ));
        $this->addColumn('category', 'tags', 'string', '255', array(
             ));
        $this->addColumn('page', 'tags', 'string', '255', array(
             ));
        $this->addColumn('product', 'tags', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog', 'tags');
        $this->removeColumn('category', 'tags');
        $this->removeColumn('page', 'tags');
        $this->removeColumn('product', 'tags');
    }
}