<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'pointcreate', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'pointcreate');
    }
}