<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version86 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('logs404', 'urlfrom', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('logs404', 'urlfrom');
    }
}