<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version88 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('articlecatalog', 'content', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('articlecatalog', 'content');
    }
}