<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version89 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('articlecatalog', 'slug', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('articlecatalog', 'slug');
    }
}