<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version104 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('news_page', 'news_page_news_id_news_id', array(
             'name' => 'news_page_news_id_news_id',
             'local' => 'news_id',
             'foreign' => 'id',
             'foreignTable' => 'news',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('news_page', 'news_page_page_id_page_id', array(
             'name' => 'news_page_page_id_page_id',
             'local' => 'page_id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('news_page', 'news_page_news_id', array(
             'fields' => 
             array(
              0 => 'news_id',
             ),
             ));
        $this->addIndex('news_page', 'news_page_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('news_page', 'news_page_news_id_news_id');
        $this->dropForeignKey('news_page', 'news_page_page_id_page_id');
        $this->removeIndex('news_page', 'news_page_news_id', array(
             'fields' => 
             array(
              0 => 'news_id',
             ),
             ));
        $this->removeIndex('news_page', 'news_page_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
    }
}