<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version103 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('news_page', array(
             'news_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'page_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'news_id',
              1 => 'page_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('news_page');
    }
}