<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version111 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('shops', 'indoorplace');
        $this->removeColumn('shops', 'worktime');
    }

    public function down()
    {
        $this->addColumn('shops', 'indoorplace', 'string', '255', array(
             ));
        $this->addColumn('shops', 'worktime', 'string', '255', array(
             ));
    }
}