<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version112 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('page', 'city_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('page', 'city_id');
    }
}