<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version109 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('shops', 'shops_city_id_city_id', array(
             'name' => 'shops_city_id_city_id',
             'local' => 'city_id',
             'foreign' => 'id',
             'foreignTable' => 'city',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('shops', 'shops_city_id', array(
             'fields' => 
             array(
              0 => 'city_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('shops', 'shops_city_id_city_id');
        $this->removeIndex('shops', 'shops_city_id', array(
             'fields' => 
             array(
              0 => 'city_id',
             ),
             ));
    }
}