<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version118 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comments', 'answer', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('comments', 'answer');
    }
}