<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version120 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('product', 'yamarket_dress');
        $this->addColumn('product', 'yamarket_clothes', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->addColumn('product', 'yamarket_dress', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('product', 'yamarket_clothes');
    }
}