<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version119 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'yamarket_dress', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('product', 'yamarket_color', 'string', '255', array(
             ));
        $this->addColumn('product', 'yamarket_typeimg', 'string', '255', array(
             ));
        $this->addColumn('product', 'yamarket_category', 'string', '255', array(
             ));
        $this->addColumn('product', 'yamarket_sex', 'enum', '', array(
             'values' => 
             array(
              0 => '',
              1 => 'Женский',
              2 => 'Мужской',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'yamarket_dress');
        $this->removeColumn('product', 'yamarket_color');
        $this->removeColumn('product', 'yamarket_typeimg');
        $this->removeColumn('product', 'yamarket_category');
        $this->removeColumn('product', 'yamarket_sex');
    }
}