<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version124 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('orders_shop', 'date', 'timestamp', '25', array(
             ));
    }

    public function down()
    {

    }
}