<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version123 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('orders_shop', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'text' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'dopid' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'checknumber' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'smena' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'discountcard' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'cardownername' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'cardowner' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'price' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('orders_shop');
    }
}