<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version130 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'status_detail', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'status_detail');
    }
}