<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version125 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('oprosnik', 'rating', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('oprosnik', 'rating');
    }
}