<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version132 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'manager', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'manager');
    }
}