<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version128 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('mail_templates', 'slug', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
    }

    public function down()
    {

    }
}