<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version136 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dop_info_category_full_dop_info', 'dddi_4', array(
             'name' => 'dddi_4',
             'local' => 'dop_info_category_full_id',
             'foreign' => 'id',
             'foreignTable' => 'dop_info_category_full',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_id_dop_info_id', array(
             'name' => 'dop_info_category_full_dop_info_dop_info_id_dop_info_id',
             'local' => 'dop_info_id',
             'foreign' => 'id',
             'foreignTable' => 'dop_info',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_category_full_id', array(
             'fields' => 
             array(
              0 => 'dop_info_category_full_id',
             ),
             ));
        $this->addIndex('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_id', array(
             'fields' => 
             array(
              0 => 'dop_info_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dop_info_category_full_dop_info', 'dddi_4');
        $this->dropForeignKey('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_id_dop_info_id');
        $this->removeIndex('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_category_full_id', array(
             'fields' => 
             array(
              0 => 'dop_info_category_full_id',
             ),
             ));
        $this->removeIndex('dop_info_category_full_dop_info', 'dop_info_category_full_dop_info_dop_info_id', array(
             'fields' => 
             array(
              0 => 'dop_info_id',
             ),
             ));
    }
}