<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version135 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dop_info_category_full_dop_info', array(
             'dop_info_category_full_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'dop_info_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'dop_info_category_full_id',
              1 => 'dop_info_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('dop_info_category_full_dop_info');
    }
}