<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version138 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'bonuspay', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'bonuspay');
    }
}