<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version143 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('horoscope', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'date' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'image' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '50',
             ),
             'info' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'month' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'year' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'characteristic' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'compatibility' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('horoscope');
    }
}