<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version146 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tests_question', 'tests_question_test_id_tests_id', array(
             'name' => 'tests_question_test_id_tests_id',
             'local' => 'test_id',
             'foreign' => 'id',
             'foreignTable' => 'tests',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tests_question_answer', 'tests_question_answer_testquestion_id_tests_question_id', array(
             'name' => 'tests_question_answer_testquestion_id_tests_question_id',
             'local' => 'testquestion_id',
             'foreign' => 'id',
             'foreignTable' => 'tests_question',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tests_question', 'tests_question_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
        $this->addIndex('tests_question_answer', 'tests_question_answer_testquestion_id', array(
             'fields' => 
             array(
              0 => 'testquestion_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tests_question', 'tests_question_test_id_tests_id');
        $this->dropForeignKey('tests_question_answer', 'tests_question_answer_testquestion_id_tests_question_id');
        $this->removeIndex('tests_question', 'tests_question_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
        $this->removeIndex('tests_question_answer', 'tests_question_answer_testquestion_id', array(
             'fields' => 
             array(
              0 => 'testquestion_id',
             ),
             ));
    }
}