<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version149 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tests_result', 'tests_result_test_id_tests_id', array(
             'name' => 'tests_result_test_id_tests_id',
             'local' => 'test_id',
             'foreign' => 'id',
             'foreignTable' => 'tests',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tests_result', 'tests_result_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tests_result', 'tests_result_test_id_tests_id');
        $this->removeIndex('tests_result', 'tests_result_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
    }
}