<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version153 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog', 'title', 'string', '255', array(
             ));
        $this->addColumn('catalog', 'keywords', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog', 'title');
        $this->removeColumn('catalog', 'keywords');
    }
}