<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version165 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'page_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('shops', 'page_id');
    }
}