<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version166 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('shops', 'shops_page_id_page_id', array(
             'name' => 'shops_page_id_page_id',
             'local' => 'page_id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             ));
        $this->addIndex('shops', 'shops_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('shops', 'shops_page_id_page_id');
        $this->removeIndex('shops', 'shops_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
    }
}