<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version164 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'firsttext', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'firsttext');
    }
}