<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version170 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('compare', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'products' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'rule' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Личный',
              1 => 'Доступен со ссылкой',
              2 => 'Публичный',
              ),
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('comments', 'compare_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('compare');
        $this->removeColumn('comments', 'compare_id');
    }
}