<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version169 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'yamarket_model', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'yamarket_model');
    }
}