<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version172 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('compare', 'products', 'clob', '', array(
             ));
    }

    public function down()
    {

    }
}