<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version178 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders_shop', 'ipactive', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders_shop', 'ipactive');
    }
}