<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version180 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('photos_user', 'photos_user_user_id_sf_guard_user_id', array(
             'name' => 'photos_user_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('photos_user', 'photos_user_product_id_product_id', array(
             'name' => 'photos_user_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('photos_user', 'photos_user_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('photos_user', 'photos_user_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('photos_user', 'photos_user_user_id_sf_guard_user_id');
        $this->dropForeignKey('photos_user', 'photos_user_product_id_product_id');
        $this->removeIndex('photos_user', 'photos_user_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('photos_user', 'photos_user_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}