<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version184 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('comments', 'rateplus');
        $this->removeColumn('comments', 'rateminus');
        $this->addColumn('comments', 'rate_plus', 'integer', '8', array(
             ));
        $this->addColumn('comments', 'rate_minus', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('comments', 'rateplus', 'integer', '8', array(
             ));
        $this->addColumn('comments', 'rateminus', 'integer', '8', array(
             ));
        $this->removeColumn('comments', 'rate_plus');
        $this->removeColumn('comments', 'rate_minus');
    }
}