<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version186 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'buywithitem', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'buywithitem');
    }
}