<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version194 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'is_visiblechildren', 'boolean', '25', array(
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'is_visiblechildren');
    }
}