<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version196 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders', 'sms_price', 'string', '255', array(
             ));
        $this->addColumn('orders', 'sms_currency', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders', 'sms_price');
        $this->removeColumn('orders', 'sms_currency');
    }
}