<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version197 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'iconmetro', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('shops', 'iconmetro');
    }
}