<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version201 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('actions_discount_interval', 'actions_discount_interval_actionsdiscount_id_actions_discount_id', array(
             'name' => 'actions_discount_interval_actionsdiscount_id_actions_discount_id',
             'local' => 'actionsdiscount_id',
             'foreign' => 'id',
             'foreignTable' => 'actions_discount',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('actions_discount_interval', 'actions_discount_interval_actionsdiscount_id', array(
             'fields' => 
             array(
              0 => 'actionsdiscount_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('actions_discount_interval', 'actions_discount_interval_actionsdiscount_id_actions_discount_id');
        $this->removeIndex('actions_discount_interval', 'actions_discount_interval_actionsdiscount_id', array(
             'fields' => 
             array(
              0 => 'actionsdiscount_id',
             ),
             ));
    }
}