<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version204 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('notification_category', 'notification_category_category_id_category_id');
    }

    public function down()
    {
        $this->createForeignKey('notification_category', 'notification_category_category_id_category_id', array(
             'name' => 'notification_category_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }
}