<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version205 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('video', 'is_publicmainpage', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('video', 'is_publicmainpage');
    }
}