<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version206 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('video', 'tag', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('video', 'tag');
    }
}