<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version208 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('page', 'is_show_right_block', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('page', 'is_show_right_block');
    }
}