<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version211 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders_shop', 'dateactive', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orders_shop', 'dateactive');
    }
}