<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version210 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'rrproductid', 'clob', '', array(
             ));
        $this->addColumn('category', 'lastupdaterrproductid', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'rrproductid');
        $this->removeColumn('category', 'lastupdaterrproductid');
    }
}