<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version214 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('oprosnik', 'shop', 'enum', '', array(
             'values' => 
             array(
              0 => 'Магазин',
              1 => 'Интернет магазин',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('oprosnik', 'shop');
    }
}