<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version215 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog', 'randomprod', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog', 'randomprod');
    }
}