<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version217 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'filtersnew', 'clob', '', array(
             ));
        $this->addColumn('category', 'minprice', 'integer', '8', array(
             ));
        $this->addColumn('category', 'maxprice', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'filtersnew');
        $this->removeColumn('category', 'minprice');
        $this->removeColumn('category', 'maxprice');
    }
}