<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version223 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'is_notadddelivery', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'is_notadddelivery');
    }
}