<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version233 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('city', 'is_public', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('city', 'is_public');
    }
}