<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version231 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('city', 'slug', 'string', '255', array(
             ));
        $this->addColumn('city', 'pickpointpage', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('city', 'slug');
        $this->removeColumn('city', 'pickpointpage');
    }
}