<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version234 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comments', 'point', 'integer', '8', array(
             ));
        $this->addColumn('comments', 'comment_manager', 'clob', '', array(
             ));
        $this->addColumn('photos_user', 'point', 'integer', '8', array(
             ));
        $this->addColumn('photos_user', 'comment_manager', 'clob', '', array(
             ));
        $this->addColumn('video', 'point', 'integer', '8', array(
             ));
        $this->addColumn('video', 'comment_manager', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('comments', 'point');
        $this->removeColumn('comments', 'comment_manager');
        $this->removeColumn('photos_user', 'point');
        $this->removeColumn('photos_user', 'comment_manager');
        $this->removeColumn('video', 'point');
        $this->removeColumn('video', 'comment_manager');
    }
}