<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version235 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('comments', 'manager_id', 'integer', '8', array(
             ));
        $this->addColumn('photos_user', 'manager_id', 'integer', '8', array(
             ));
        $this->addColumn('video', 'manager_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('comments', 'manager_id');
        $this->removeColumn('photos_user', 'manager_id');
        $this->removeColumn('video', 'manager_id');
    }
}