<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version237 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('video', 'is_public', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('video', 'is_publicmainpage', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}