<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version236 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('photos_user', 'username', 'string', '255', array(
             ));
        $this->addColumn('video', 'username', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('photos_user', 'username');
        $this->removeColumn('video', 'username');
    }
}