<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version241 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('article', 'moder', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('article', 'user', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('article', 'moder');
        $this->removeColumn('article', 'user');
    }
}