<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version247 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('russian_post_city', 'content_mo', 'clob', '', array(
             ));
        $this->addColumn('russian_post_city', 'content_mo_mobile', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('russian_post_city', 'content_mo');
        $this->removeColumn('russian_post_city', 'content_mo_mobile');
    }
}