generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Validw3
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          validw3
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [ pageurl, error, updated_at ]
      filter:  ~
      form:    
        display: 
          Основная информация: [ pageurl, error, _page ]
      edit:    ~
      new:     ~
