generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Vacancy
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vacancy
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:
          label: Название
        content:
          label: Описание вакансии
        is_public:
          label: Активна
        position:
          label: Сортировка
      list:
        title: Вакансии
        display: [ id, name, is_public, position ]
      filter:
        display: [ id, name, is_public ]
      form:
        display:
          Основная информация: [ name, content, position, is_public]
      edit:
        title: Редактирование вакансии "%%name%%"
      new:
        title: Создание вакансии
